name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  packages:
    name: "Build packages"
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
      
    - name: create draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: Show changes in this release
        draft: true
        prerelease: false
  
    - name: install_deps
      run: make install_deps
    - name: build_deb
      run: make build_deb
    - name: build_rpm
      run: make build_rpm
    - name: build_snap
      run: make build_snap
    - name: build_appimage
      run: make build_appimage
    - name: build_7z
      run: make build_7z
