name: Build

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  packages:
    name: "Build packages"
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: build
      run: make build_pkgs
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: artifacts/x64/*.*
